// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminUpdateBookingStatus = `-- name: AdminUpdateBookingStatus :one
UPDATE bookings
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, service_id, booking_time, status, notes, created_at, updated_at
`

type AdminUpdateBookingStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) AdminUpdateBookingStatus(ctx context.Context, arg AdminUpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, adminUpdateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.BookingTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    user_id, service_id, booking_time, status, notes
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, service_id, booking_time, status, notes, created_at, updated_at
`

type CreateBookingParams struct {
	UserID      pgtype.UUID
	ServiceID   pgtype.UUID
	BookingTime pgtype.Timestamptz
	Status      string
	Notes       pgtype.Text
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.ServiceID,
		arg.BookingTime,
		arg.Status,
		arg.Notes,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.BookingTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT 
    b.id,
    b.user_id,
    b.service_id,
    b.booking_time,
    b.status,
    b.notes,
    b.created_at,
    b.updated_at,
    s.title as service_title,
    s.price as service_price,
    s.duration_minutes as service_duration
FROM bookings b
JOIN services s ON b.service_id = s.id
WHERE b.id = $1 LIMIT 1
`

type GetBookingByIDRow struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	ServiceID       pgtype.UUID
	BookingTime     pgtype.Timestamptz
	Status          string
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ServiceTitle    string
	ServicePrice    pgtype.Numeric
	ServiceDuration int32
}

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.BookingTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceTitle,
		&i.ServicePrice,
		&i.ServiceDuration,
	)
	return i, err
}

const listAllBookings = `-- name: ListAllBookings :many
SELECT 
    b.id,
    b.user_id,
    b.service_id,
    b.booking_time,
    b.status,
    b.notes,
    b.created_at,
    b.updated_at,
    s.title as service_title,
    s.price as service_price,
    s.duration_minutes as service_duration,
    s.image_url as service_image_url,
    s.category as service_category,
    u.name as user_name,
    u.email as user_email,
    u.phone as user_phone,
    u.phone_verified as user_phone_verified
FROM bookings b
JOIN services s ON b.service_id = s.id
JOIN users u ON b.user_id = u.id
ORDER BY b.booking_time DESC
`

type ListAllBookingsRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	ServiceID         pgtype.UUID
	BookingTime       pgtype.Timestamptz
	Status            string
	Notes             pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ServiceTitle      string
	ServicePrice      pgtype.Numeric
	ServiceDuration   int32
	ServiceImageUrl   string
	ServiceCategory   string
	UserName          string
	UserEmail         pgtype.Text
	UserPhone         pgtype.Text
	UserPhoneVerified bool
}

func (q *Queries) ListAllBookings(ctx context.Context) ([]ListAllBookingsRow, error) {
	rows, err := q.db.Query(ctx, listAllBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBookingsRow
	for rows.Next() {
		var i ListAllBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.BookingTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceTitle,
			&i.ServicePrice,
			&i.ServiceDuration,
			&i.ServiceImageUrl,
			&i.ServiceCategory,
			&i.UserName,
			&i.UserEmail,
			&i.UserPhone,
			&i.UserPhoneVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUserID = `-- name: ListBookingsByUserID :many
SELECT 
    b.id,
    b.user_id,
    b.service_id,
    b.booking_time,
    b.status,
    b.notes,
    b.created_at,
    b.updated_at,
    s.title as service_title,
    s.price as service_price,
    s.duration_minutes as service_duration,
    s.image_url as service_image_url
FROM bookings b
JOIN services s ON b.service_id = s.id
WHERE b.user_id = $1
ORDER BY b.booking_time DESC
`

type ListBookingsByUserIDRow struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	ServiceID       pgtype.UUID
	BookingTime     pgtype.Timestamptz
	Status          string
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ServiceTitle    string
	ServicePrice    pgtype.Numeric
	ServiceDuration int32
	ServiceImageUrl string
}

func (q *Queries) ListBookingsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListBookingsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsByUserIDRow
	for rows.Next() {
		var i ListBookingsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.BookingTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceTitle,
			&i.ServicePrice,
			&i.ServiceDuration,
			&i.ServiceImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET status = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, service_id, booking_time, status, notes, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID     pgtype.UUID
	Status string
	UserID pgtype.UUID
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.BookingTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
