// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gallery.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGalleryImage = `-- name: CreateGalleryImage :one
INSERT INTO gallery_images (
    url, caption, order_index
) VALUES (
    $1, $2, $3
) RETURNING id, url, caption, order_index, created_at
`

type CreateGalleryImageParams struct {
	Url        string
	Caption    pgtype.Text
	OrderIndex int32
}

func (q *Queries) CreateGalleryImage(ctx context.Context, arg CreateGalleryImageParams) (GalleryImage, error) {
	row := q.db.QueryRow(ctx, createGalleryImage, arg.Url, arg.Caption, arg.OrderIndex)
	var i GalleryImage
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Caption,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listGalleryImages = `-- name: ListGalleryImages :many
SELECT id, url, caption, order_index, created_at FROM gallery_images
ORDER BY order_index ASC, created_at DESC
`

func (q *Queries) ListGalleryImages(ctx context.Context) ([]GalleryImage, error) {
	rows, err := q.db.Query(ctx, listGalleryImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GalleryImage
	for rows.Next() {
		var i GalleryImage
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Caption,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
