// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	ServiceID   pgtype.UUID
	BookingTime pgtype.Timestamptz
	Status      string
	Notes       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GalleryImage struct {
	ID         pgtype.UUID
	Url        string
	Caption    pgtype.Text
	OrderIndex int32
	CreatedAt  pgtype.Timestamptz
}

type OtpCode struct {
	ID        pgtype.UUID
	Phone     string
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
	Attempts  int32
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Service struct {
	ID              pgtype.UUID
	Title           string
	Description     string
	Price           pgtype.Numeric
	DurationMinutes int32
	ImageUrl        string
	Category        string
	CreatedAt       pgtype.Timestamptz
}

type Ticket struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Subject   string
	Status    string
	Priority  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TicketMessage struct {
	ID          pgtype.UUID
	TicketID    pgtype.UUID
	SenderID    pgtype.UUID
	SenderRole  string
	Message     string
	IsEmailSent bool
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Name          string
	Email         pgtype.Text
	Phone         pgtype.Text
	PasswordHash  pgtype.Text
	GoogleID      pgtype.Text
	PhoneVerified bool
	Role          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
