// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (
    phone, code_hash, expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, phone, code_hash, expires_at, attempts, created_at
`

type CreateOTPParams struct {
	Phone     string
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP, arg.Phone, arg.CodeHash, arg.ExpiresAt)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOTPsForPhone = `-- name: DeleteOTPsForPhone :exec
DELETE FROM otp_codes
WHERE phone = $1
`

func (q *Queries) DeleteOTPsForPhone(ctx context.Context, phone string) error {
	_, err := q.db.Exec(ctx, deleteOTPsForPhone, phone)
	return err
}

const getLatestValidOTP = `-- name: GetLatestValidOTP :one
SELECT id, phone, code_hash, expires_at, attempts, created_at FROM otp_codes
WHERE phone = $1 AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestValidOTP(ctx context.Context, phone string) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestValidOTP, phone)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}
