// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    title, description, price, duration_minutes, image_url, category
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, title, description, price, duration_minutes, image_url, category, created_at
`

type CreateServiceParams struct {
	Title           string
	Description     string
	Price           pgtype.Numeric
	DurationMinutes int32
	ImageUrl        string
	Category        string
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.DurationMinutes,
		arg.ImageUrl,
		arg.Category,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.ImageUrl,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, title, description, price, duration_minutes, image_url, category, created_at FROM services
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.ImageUrl,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, title, description, price, duration_minutes, image_url, category, created_at FROM services
ORDER BY category, price ASC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.DurationMinutes,
			&i.ImageUrl,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET title = $2,
    description = $3,
    price = $4,
    duration_minutes = $5,
    image_url = $6,
    category = $7
WHERE id = $1
RETURNING id, title, description, price, duration_minutes, image_url, category, created_at
`

type UpdateServiceParams struct {
	ID              pgtype.UUID
	Title           string
	Description     string
	Price           pgtype.Numeric
	DurationMinutes int32
	ImageUrl        string
	Category        string
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.DurationMinutes,
		arg.ImageUrl,
		arg.Category,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.DurationMinutes,
		&i.ImageUrl,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}
