// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    user_id, subject, status, priority
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, subject, status, priority, created_at, updated_at
`

type CreateTicketParams struct {
	UserID   pgtype.UUID
	Subject  string
	Status   string
	Priority string
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.UserID,
		arg.Subject,
		arg.Status,
		arg.Priority,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketMessage = `-- name: CreateTicketMessage :one
INSERT INTO ticket_messages (
    ticket_id, sender_id, sender_role, message, is_email_sent
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, ticket_id, sender_id, sender_role, message, is_email_sent, created_at
`

type CreateTicketMessageParams struct {
	TicketID    pgtype.UUID
	SenderID    pgtype.UUID
	SenderRole  string
	Message     string
	IsEmailSent bool
}

func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketMessage, error) {
	row := q.db.QueryRow(ctx, createTicketMessage,
		arg.TicketID,
		arg.SenderID,
		arg.SenderRole,
		arg.Message,
		arg.IsEmailSent,
	)
	var i TicketMessage
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.SenderID,
		&i.SenderRole,
		&i.Message,
		&i.IsEmailSent,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT 
    t.id,
    t.user_id,
    t.subject,
    t.status,
    t.priority,
    t.created_at,
    t.updated_at,
    u.name as user_name,
    u.email as user_email,
    u.phone as user_phone
FROM tickets t
JOIN users u ON t.user_id = u.id
WHERE t.id = $1 LIMIT 1
`

type GetTicketByIDRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Subject   string
	Status    string
	Priority  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserName  string
	UserEmail pgtype.Text
	UserPhone pgtype.Text
}

func (q *Queries) GetTicketByID(ctx context.Context, id pgtype.UUID) (GetTicketByIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i GetTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserPhone,
	)
	return i, err
}

const listAllTickets = `-- name: ListAllTickets :many
SELECT 
    t.id,
    t.user_id,
    t.subject,
    t.status,
    t.priority,
    t.created_at,
    t.updated_at,
    u.name as user_name,
    u.email as user_email,
    u.phone as user_phone
FROM tickets t
JOIN users u ON t.user_id = u.id
ORDER BY t.updated_at DESC
`

type ListAllTicketsRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Subject   string
	Status    string
	Priority  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserName  string
	UserEmail pgtype.Text
	UserPhone pgtype.Text
}

func (q *Queries) ListAllTickets(ctx context.Context) ([]ListAllTicketsRow, error) {
	rows, err := q.db.Query(ctx, listAllTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTicketsRow
	for rows.Next() {
		var i ListAllTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Subject,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketMessages = `-- name: ListTicketMessages :many
SELECT 
    tm.id,
    tm.ticket_id,
    tm.sender_id,
    tm.sender_role,
    tm.message,
    tm.is_email_sent,
    tm.created_at,
    u.name as sender_name,
    u.email as sender_email
FROM ticket_messages tm
JOIN users u ON tm.sender_id = u.id
WHERE tm.ticket_id = $1
ORDER BY tm.created_at ASC
`

type ListTicketMessagesRow struct {
	ID          pgtype.UUID
	TicketID    pgtype.UUID
	SenderID    pgtype.UUID
	SenderRole  string
	Message     string
	IsEmailSent bool
	CreatedAt   pgtype.Timestamptz
	SenderName  string
	SenderEmail pgtype.Text
}

func (q *Queries) ListTicketMessages(ctx context.Context, ticketID pgtype.UUID) ([]ListTicketMessagesRow, error) {
	rows, err := q.db.Query(ctx, listTicketMessages, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketMessagesRow
	for rows.Next() {
		var i ListTicketMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.SenderID,
			&i.SenderRole,
			&i.Message,
			&i.IsEmailSent,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByUserID = `-- name: ListTicketsByUserID :many
SELECT 
    t.id,
    t.user_id,
    t.subject,
    t.status,
    t.priority,
    t.created_at,
    t.updated_at,
    u.name as user_name,
    u.email as user_email
FROM tickets t
JOIN users u ON t.user_id = u.id
WHERE t.user_id = $1
ORDER BY t.updated_at DESC
`

type ListTicketsByUserIDRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Subject   string
	Status    string
	Priority  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserName  string
	UserEmail pgtype.Text
}

func (q *Queries) ListTicketsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListTicketsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listTicketsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsByUserIDRow
	for rows.Next() {
		var i ListTicketsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Subject,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, subject, status, priority, created_at, updated_at
`

type UpdateTicketStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.ID, arg.Status)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
