// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, email, phone, password_hash, google_id, phone_verified, role
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at
`

type CreateUserParams struct {
	Name          string
	Email         pgtype.Text
	Phone         pgtype.Text
	PasswordHash  pgtype.Text
	GoogleID      pgtype.Text
	PhoneVerified bool
	Role          string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.GoogleID,
		arg.PhoneVerified,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.PhoneVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.PhoneVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.PhoneVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.PhoneVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at FROM users
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.PhoneVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.GoogleID,
			&i.PhoneVerified,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPhoneVerified = `-- name: UpdateUserPhoneVerified :one
UPDATE users
SET phone_verified = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at
`

type UpdateUserPhoneVerifiedParams struct {
	ID            pgtype.UUID
	PhoneVerified bool
}

func (q *Queries) UpdateUserPhoneVerified(ctx context.Context, arg UpdateUserPhoneVerifiedParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPhoneVerified, arg.ID, arg.PhoneVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.PhoneVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $2,
    phone = $3,
    phone_verified = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID            pgtype.UUID
	Name          string
	Phone         pgtype.Text
	PhoneVerified bool
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.PhoneVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.PhoneVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :one
INSERT INTO users (
    name, email, google_id, role
) VALUES (
    $1, $2, $3, 'customer'
)
ON CONFLICT (email) DO UPDATE
SET google_id = EXCLUDED.google_id,
    name = CASE WHEN users.name = '' THEN EXCLUDED.name ELSE users.name END,
    updated_at = NOW()
RETURNING id, name, email, phone, password_hash, google_id, phone_verified, role, created_at, updated_at
`

type UpsertGoogleUserParams struct {
	Name     string
	Email    pgtype.Text
	GoogleID pgtype.Text
}

func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUser, arg.Name, arg.Email, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.GoogleID,
		&i.PhoneVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
